version: "3.8"

services:
  app:
    build:
      args:
        user: Renato
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: infolivre/laravel-app
    working_dir: /var/www/
    volumes: 
      - ./:/var/www
    restart: unless-stopped
    networks:
      - docker-laravel
      
#Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - docker-laravel

networks:
  docker-laravel:
    driver: bridge